artifact_location: file:.C:\Users\jeanc\git_projects\Machine-Learning-Model-for-Predicting-Value-Condition\src\storage\mlflow_artifacts/589703336745971951
creation_time: 1767197622011
experiment_id: '589703336745971951'
last_update_time: 1767197622011
lifecycle_stage: active
name: Valve Condition Predictor
