artifact_uri: file:C:\Users\jeanc\git_projects\Machine-Learning-Model-for-Predicting-Value-Condition\src\storage\mlflow_artifacts/399588728512772674/f4ee4c3aa6a542369e5a1594697d7951/artifacts
end_time: 1766283653781
entry_point_name: ''
experiment_id: '399588728512772674'
lifecycle_stage: active
run_id: f4ee4c3aa6a542369e5a1594697d7951
run_name: best_RandomForestClassifier
run_uuid: f4ee4c3aa6a542369e5a1594697d7951
source_name: ''
source_type: 4
source_version: ''
start_time: 1766283651008
status: 3
tags: []
user_id: jeanc
