aliases: []
creation_timestamp: 1767233851993
current_stage: None
description: null
last_updated_timestamp: 1767233851993
name: valve_condition_model
run_id: eb05f1dad7b1408ea7b91236c9873372
run_link: null
source: file:.C:\Users\jeanc\git_projects\Machine-Learning-Model-for-Predicting-Value-Condition\src\storage\mlflow_artifacts/589703336745971951/eb05f1dad7b1408ea7b91236c9873372/artifacts/models
status: READY
status_message: null
storage_location: file:.C:\Users\jeanc\git_projects\Machine-Learning-Model-for-Predicting-Value-Condition\src\storage\mlflow_artifacts/589703336745971951/eb05f1dad7b1408ea7b91236c9873372/artifacts/models
user_id: null
version: 7
