channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=25.0.1
- pip:
  - mlflow==2.10.0
  - cloudpickle==3.1.2
  - numpy==1.24.3
  - packaging==23.2
  - psutil==5.9.8
  - pyyaml==5.1.2
  - scikit-learn==1.3.0
  - scipy==1.9.3
name: mlflow-env
