artifact_uri: file:C:\Users\jeanc\git_projects\Machine-Learning-Model-for-Predicting-Value-Condition\src\storage\mlflow_artifacts/399588728512772674/fb5e545f9a9843849ff37aeb17e4933f/artifacts
end_time: 1766283525878
entry_point_name: ''
experiment_id: '399588728512772674'
lifecycle_stage: active
run_id: fb5e545f9a9843849ff37aeb17e4933f
run_name: best_RandomForestClassifier
run_uuid: fb5e545f9a9843849ff37aeb17e4933f
source_name: ''
source_type: 4
source_version: ''
start_time: 1766283523036
status: 3
tags: []
user_id: jeanc
