artifact_location: file:C:\Users\jeanc\git_projects\Machine-Learning-Model-for-Predicting-Value-Condition\src\storage\mlflow_artifacts/399588728512772674
creation_time: 1766283508881
experiment_id: '399588728512772674'
last_update_time: 1766283508881
lifecycle_stage: active
name: Valve Condition Predictor
