aliases: []
creation_timestamp: 1766286473675
current_stage: None
description: null
last_updated_timestamp: 1766286473675
name: valve_condition_model
run_id: 118eae91cfb34e408b064134750814f0
run_link: null
source: file:C:\Users\jeanc\git_projects\Machine-Learning-Model-for-Predicting-Value-Condition\src\storage\mlflow_artifacts/399588728512772674/118eae91cfb34e408b064134750814f0/artifacts/models
status: READY
status_message: null
storage_location: file:C:\Users\jeanc\git_projects\Machine-Learning-Model-for-Predicting-Value-Condition\src\storage\mlflow_artifacts/399588728512772674/118eae91cfb34e408b064134750814f0/artifacts/models
user_id: null
version: 3
