aliases: []
creation_timestamp: 1766283525842
current_stage: None
description: null
last_updated_timestamp: 1766283525842
name: valve_condition_model
run_id: fb5e545f9a9843849ff37aeb17e4933f
run_link: null
source: file:C:\Users\jeanc\git_projects\Machine-Learning-Model-for-Predicting-Value-Condition\src\storage\mlflow_artifacts/399588728512772674/fb5e545f9a9843849ff37aeb17e4933f/artifacts/models
status: READY
status_message: null
storage_location: file:C:\Users\jeanc\git_projects\Machine-Learning-Model-for-Predicting-Value-Condition\src\storage\mlflow_artifacts/399588728512772674/fb5e545f9a9843849ff37aeb17e4933f/artifacts/models
user_id: null
version: 1
